### DISCUSSION TITLE
Problem deploying Consumer/Provider connectors of "Transfer sample 00: Prerequisites" using Docker

### DISCUSSION THREAD

**Discussion by jonlega06** [eclipse-edc/Samples#193] [Q&A]
Hello everyone, 

I have started to make the examples of this EDC repository, as I intend to start working with EDC to implement it in some project. And I'm having problems to deploy the connectors (both consumer and producer) of the "Transfer sample 00: Prerequisites" example using **Docker**. In the previous examples I managed to deploy it correctly but in this case with the new dependencies and plugins I can't solve the error. For the deployment I first define a Dockerfile to build the image that I will use with the .jar of the application. Below is the one I have used:

```Dockerfile
FROM gradle:jdk17 AS build

WORKDIR /home/gradle/project/
COPY --chown=gradle:gradle . /home/gradle/project/
RUN gradle transfer:transfer-00-prerequisites:connector:build

FROM openjdk:17-slim

WORKDIR /app

COPY --from=build /home/gradle/project/transfer/transfer-00-prerequisites/connector/build/libs/*.jar /app/app.jar
```

Then using a docker-compose, I define the template to deploy both consumer/provider containers on the same Docker network with their respective variables and ports.

```yaml
version: "3.8"

services:
  consumer:
    build:
      context: ../..
      dockerfile: transfer/transfer-00-prerequisites/connector/Dockerfile
    container_name: edc-consumer
    hostname: edc-consumer
    ports:
      - "29191:29191" # Http
      - "29192:29192" # Control
      - "29193:29193" # Management
      - "29194:29194" # DSP
      - "29291:29291" # Public
      - "4000:4000"   # Receiver

    environment:
      EDC_KEYSTORE: /config/certs/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_VAULT: /config/configuration/consumer-vault.properties
      EDC_FS_CONFIG: /config/configuration/consumer-config.properties
    volumes:
      - ./resources:/config
    entrypoint: ["java", "-jar", "/app/app.jar"]

  provider:
    build:
      context: ../..
      dockerfile: transfer/transfer-00-prerequisites/connector/Dockerfile
    container_name: edc-provider
    hostname: edc-provider
    ports:
      - "19191:19191" # Http 
      - "19192:19192" # Control
      - "19193:19193" # Management 
      - "19194:19194" # DSP
      - "19291:19291" # Public
      - "4001:4000"   # Receiver
    environment:
      EDC_KEYSTORE: /config/certs/cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_VAULT: /config/configuration/provider-vault.properties
      EDC_FS_CONFIG: /config/configuration/provider-config.properties
    volumes:
      - ./resources:/config
    entrypoint: ["java", "-jar", "/app/app.jar"]

````

The problem comes with the "edc.receiver.http.endpoint" parameter of both connectors as indicated in the container logs: **"org.eclipse.edc.spi.EdcException: Missing mandatory http receiver endpoint: `edc.receiver.http.endpoint`"**. This parameter that is defined in the configuration files of both connectors was defined as localhost at the beginning, but after modifying the parameters by the dns names of the docker network it seems that the connectors don't manage to connect to the endpoint. Below is the provider configuration file:

```.properties
edc.participant.id=provider
edc.dsp.callback.address=http://edc-provider:19194/protocol
web.http.port=19191
web.http.path=/api
web.http.management.port=19193
web.http.management.path=/management
web.http.protocol.port=19194
web.http.protocol.path=/protocol
edc.receiver.http.endpoint=http://edc-consumer:4000/receiver/urn:connector:provider/callback
edc.public.key.alias=public-key
edc.transfer.dataplane.token.signer.privatekey.alias=1
edc.transfer.proxy.token.signer.privatekey.alias=1
edc.transfer.proxy.token.verifier.publickey.alias=public-key
web.http.public.port=19291
web.http.public.path=/public
web.http.control.port=19192
web.http.control.path=/control
edc.dataplane.token.validation.endpoint=http://edc-provider:19192/control/token
```

I have tried swapping the names of the containers in the configuration file but I still can't get them deployed without error. Maybe my problem is that I am not understanding how the "edc.receiver.http.endpoint" service works correctly. Could someone help me to deploy the connectors correctly and follow the transfer tutorial? 

Thanks in advance for your assistance!

Jon
