### ISSUE TITLE
Can't initiate a transfer on S3 hosted Asset

### ISSUE THREAD

**Issue by skante93** [eclipse-edc/Samples#218]
# Can't initiate a transfer on S3 hosted Asset

I create a local deployment of two connectors based on the [transfer/transfer-05-file-transfer-cloud](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-05-file-transfer-cloud), but towards the end, when initiating a transfer, the consumer connector seems to send a request with the wrong format.

## Setup

This is how I proceeded (might be helpful in finding out what was wrong) : 
* I created a free account on AWS and created myself a bucket <code>skante-b1</code> containing a single jpeg image (snow.jpg), then downloaded the credentials
* I cloned the Samples repository
* I edited the [transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts](https://github.com/eclipse-edc/Samples/blob/main/transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts) file by: 
  * replacing in line 31, the line <code>implementation(libs.edc.vault.azure)</code> by  <code>implementation(libs.edc.vault.filesystem)</code>. This is because I wanted to use the local filsystem instead of an actual azure vault. I am in a development setting after all and I do not have an azure account.
  * adding the expression <code>implementation(libs.edc.data.plane.selector.api)</code> so I can add dataplanes later on through the management API
* built that connector like this (creates the resources directory and cp the jar file inside): 
```bash
docker run -it \
  -v $(pwd)/Samples:/data \
  -w /data \
  gradle:jdk17  ./gradlew transfer:transfer-05-file-transfer-cloud:cloud-transfer-consumer:build

mkdir -p resources && cp Samples/transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build/libs/consumer.jar resources/connector.jar
```
* Then I added a <code>keystore.jks</code> and a <code>vault.properties</code> file, the latter containing my AWS credentials (<code>aws-key</code> and <code>aws-secret</code>)
* Then I created the following docker compose file:

```yaml
services:
  provider:
    image: openjdk
    volumes:
      - ./resources:/app
    command:
      - java
      - -jar
      - /app/connector.jar
    environment:
      EDC_AWS_ACCESS_KEY: aws-key
      EDC_AWS_SECRET_ACCESS_KEY: aws-secret
      # EDC_AWS_ENDPOINT_OVERRIDE: http://minio:9000             
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_PARTICIPANT_ID: provider
      WEB_HTTP_PORT: 9191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 9192
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 9292
      WEB_HTTP_PROTOCOL_PATH: /protocol
      WEB_HTTP_CONTROL_PORT: 9193
      WEB_HTTP_CONTROL_PATH: /control
      WEB_HTTP_PUBLIC_PORT: 9291
      WEB_HTTP_PUBLIC_PATH: /public
      EDC_API_AUTH_KEY: password
      EDC_DSP_CALLBACK_ADDRESS: http://provider:9292/protocol
    ports:
      - 9191:9191
      - 9192:9192
      - 9292:9292

  consumer:
    image: openjdk
    volumes:
      - ./example:/example
      - ./resources:/app
    command:
      - java
      - -jar
      - /app/connector.jar
    environment:
      EDC_AWS_ACCESS_KEY: aws-key
      EDC_AWS_SECRET_ACCESS_KEY: aws-secret
      # EDC_AWS_ENDPOINT_OVERRIDE: http://minio:9000              
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_PARTICIPANT_ID: consumer
      WEB_HTTP_PORT: 8181
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 8182
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 8282
      WEB_HTTP_PROTOCOL_PATH: /protocol
      WEB_HTTP_CONTROL_PORT: 8183
      WEB_HTTP_CONTROL_PATH: /control
      WEB_HTTP_PUBLIC_PORT: 8281
      WEB_HTTP_PUBLIC_PATH: /public
      EDC_API_AUTH_KEY: password
      EDC_DSP_CALLBACK_ADDRESS: http://consumer:8282/protocol
    ports:
      - 8181:8181
      - 8182:8182
      - 8282:8282
```
* Then started the docker compose

Everything started without any accidents.

## Transfer

I logged onto the consumer connector and pretty much followed the same steps described in [transfer/transfer-01-negotiation](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-01-negotiation).
Here are the different objects created 
* consumer dataplane
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "s3-consumer-dataplane",
  "url": "http://consumer:8183/control/transfer",
  "allowedSourceTypes": [ "AmazonS3" ],
  "allowedDestTypes": [ "AmazonS3" ],
  "properties": {
    "publicApiUrl": "http://consumer:8281/public/"
  }
}
```
* provider dataplane
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "s3-provider-dataplane",
  "url": "http://provider:9193/control/transfer",
  "allowedSourceTypes": [ "AmazonS3" ],
  "allowedDestTypes": [ "AmazonS3" ],
  "properties": {
    "publicApiUrl": "http://provider:9291/public/"
  }
}
```
* asset
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "asset-1",
  "properties": {
    "contenttype": "image/jpeg",
    "type": "AmazonS3",
    "name": "snow.jpg"
  },
  "dataAddress": {
    "type": "AmazonS3",
    "region": "eu-north-1",
    "bucketName": "skante-b1"
  }
}
```
* policy
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "odrl": "http://www.w3.org/ns/odrl/2/"
  },
  "@id": "aPolicy",
  "policy": {
    "@type": "set",
    "odrl:permission": [],
    "odrl:prohibition": [],
    "odrl:obligation": []
  }
}
```
* contract
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "1",
  "accessPolicyId": "aPolicy",
  "contractPolicyId": "aPolicy",
  "assetsSelector": []
}
```
* transferprocess (after getting catalog, extracting PolicyID, creating a contractnegociation with it, then extracting the agreement ID from the latter)
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "counterPartyAddress": "http://provider:9292/protocol",
  "protocol": "dataspace-protocol-http",
  "connectorId": "consumer",
  "assetId": "asset-1",
  "contractId": "${agreementId}",
  "dataDestination": {
    "type": "AmazonS3",
    "region": "us-east-1",
    "bucketName": "edc-skante"
  },
  "transferType": {
    "contentType": "image/jpeg",
    "isFinite": true
  }
}
```

No issues appear till I reach this point.

## Issue

This is how the logs look like when I start the transfer:
```
aws-test-consumer-1  | DEBUG 2024-03-05T11:01:58.319895278 [TransferProcessManagerImpl] TransferProcess a2797031-b8fa-48ac-bcda-ff0f63be9624 is now in state INITIAL
aws-test-consumer-1  | DEBUG 2024-03-05T11:01:58.323941369 Process a2797031-b8fa-48ac-bcda-ff0f63be9624 is now INITIAL
aws-test-consumer-1  | DEBUG 2024-03-05T11:01:58.327664018 Transfer Process created a2797031-b8fa-48ac-bcda-ff0f63be9624
aws-test-consumer-1  | DEBUG 2024-03-05T11:01:59.220716336 [TransferProcessManagerImpl] TransferProcess a2797031-b8fa-48ac-bcda-ff0f63be9624 is now in state PROVISIONING
aws-test-consumer-1  | DEBUG 2024-03-05T11:01:59.228580306 TransferProcess: ID a2797031-b8fa-48ac-bcda-ff0f63be9624. Provisioning
aws-test-consumer-1  | DEBUG 2024-03-05T11:01:59.699243825 S3ProvisionPipeline: create bucket edc-skante
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:00.936238805 S3ProvisionPipeline: get user
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:01.558358822 S3ProvisionPipeline: create role for userarn:aws:iam::533267125486:user/skante
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:01.768694742 S3ProvisionPipeline: attach bucket policy to role arn:aws:iam::533267125486:role/a2797031-b8fa-48ac-bcda-ff0f63be9624
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:01.92165362 S3ProvisionPipeline: attempting to assume the role
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:02.936441126 S3ProvisionPipeline: attempting to assume the role
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:04.04679546 S3ProvisionPipeline: attempting to assume the role
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:10.293224752 S3ProvisionPipeline: attempting to assume the role
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:10.464182051 S3BucketProvisioner: Bucket request submitted: edc-skante
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:10.51392943 [TransferProcessManagerImpl] TransferProcess a2797031-b8fa-48ac-bcda-ff0f63be9624 is now in state PROVISIONED
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:11.062634746 [TransferProcessManagerImpl] TransferProcess a2797031-b8fa-48ac-bcda-ff0f63be9624 is now in state REQUESTING
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:11.073231642 TransferProcess: ID a2797031-b8fa-48ac-bcda-ff0f63be9624. Send TransferRequestMessage to http://provider:9292/protocol
aws-test-provider-1  | DEBUG 2024-03-05T11:02:11.11760743 DSP: Incoming TransferRequestMessage for class org.eclipse.edc.connector.transfer.spi.types.TransferProcess process
aws-test-provider-1  | DEBUG 2024-03-05T11:02:11.140296957 DSP: Service call failed: 'bucketName' is a mandatory attribute, 'region' is a mandatory attribute
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:11.155470909 TransferProcess: ID a2797031-b8fa-48ac-bcda-ff0f63be9624. Send TransferRequestMessage to http://provider:9292/protocol
aws-test-consumer-1  | SEVERE 2024-03-05T11:02:11.156336241 TransferProcess: ID a2797031-b8fa-48ac-bcda-ff0f63be9624. Fatal error while Send TransferRequestMessage to http://provider:9292/protocol. Error details: {"@type":"dspace:TransferError","dspace:code":"400","dspace:reason":["'bucketName' is a mandatory attribute","'region' is a mandatory attribute"],"@context":{"@vocab":"https://w3id.org/edc/v0.0.1/ns/","edc":"https://w3id.org/edc/v0.0.1/ns/","dcat":"https://www.w3.org/ns/dcat/","dct":"https://purl.org/dc/terms/","odrl":"http://www.w3.org/ns/odrl/2/","dspace":"https://w3id.org/dspace/v0.8/"}}
aws-test-consumer-1  | WARNING 2024-03-05T11:02:11.156821717 {"@type":"dspace:TransferError","dspace:code":"400","dspace:reason":["'bucketName' is a mandatory attribute","'region' is a mandatory attribute"],"@context":{"@vocab":"https://w3id.org/edc/v0.0.1/ns/","edc":"https://w3id.org/edc/v0.0.1/ns/","dcat":"https://www.w3.org/ns/dcat/","dct":"https://purl.org/dc/terms/","odrl":"http://www.w3.org/ns/odrl/2/","dspace":"https://w3id.org/dspace/v0.8/"}}
aws-test-consumer-1  | DEBUG 2024-03-05T11:02:11.158921264 [TransferProcessManagerImpl] TransferProcess a2797031-b8fa-48ac-bcda-ff0f63be9624 is now in state TERMINATED
```

I made sure to specify not only in my asset definition but also in the transfer process the required fields for the "dataAddress", but for some reason it seems it is forgotten whenever the consumer actually requests the transfer or it is ignore by the provider for somehow. Can someone help with this issue?
